"use client"

import { useRef, useState } from "react"
import { Button } from "@/components/ui/button"
import { PhotoCropModal } from "@/components/custom/photo-crop-modal"
import { HugeiconsIcon } from "@hugeicons/react"
import {
  Upload03Icon,
  Delete02Icon,
  Image01Icon,
  ReloadIcon,
  MagicWand01Icon,
} from "@hugeicons/core-free-icons"

// A company's brand assets are all derived from a single master image: upload &
// crop once, and the favicon / sidebar mark / app icon are generated by resizing
// it on a canvas. Any asset can still be individually overridden. Everything is
// kept as object URLs for now — persistence awaits a branding model on the
// company profile.
export type BrandKey = "logo" | "favicon" | "sidebarIcon" | "appIcon"

export interface Branding {
  master: string | null // the uploaded, square-cropped source
  generated: Partial<Record<BrandKey, string>> // auto-resized from master
  overrides: Partial<Record<BrandKey, string>> // manually replaced assets
}

export const EMPTY_BRANDING: Branding = {
  master: null,
  generated: {},
  overrides: {},
}

// The asset actually used = a manual override, else the auto-generated version.
export const resolveAsset = (b: Branding, k: BrandKey): string | null =>
  b.overrides[k] ?? b.generated[k] ?? null

const ASSETS: { key: BrandKey; label: string; hint: string; size: number }[] = [
  { key: "logo", label: "Company logo", hint: "Header & profile", size: 256 },
  { key: "favicon", label: "Favicon", hint: "Browser tab icon", size: 32 },
  {
    key: "sidebarIcon",
    label: "Sidebar mark",
    hint: "Collapsed sidebar",
    size: 64,
  },
  { key: "appIcon", label: "App icon", hint: "Mobile / PWA", size: 512 },
]

// Draw `src` into a size×size canvas and return a PNG object URL.
function resizeTo(src: string, size: number): Promise<string> {
  return new Promise((resolve, reject) => {
    const img = new Image()
    img.onload = () => {
      const canvas = document.createElement("canvas")
      canvas.width = size
      canvas.height = size
      const ctx = canvas.getContext("2d")!
      ctx.imageSmoothingEnabled = true
      ctx.imageSmoothingQuality = "high"
      ctx.drawImage(img, 0, 0, size, size)
      canvas.toBlob(
        (blob) =>
          blob
            ? resolve(URL.createObjectURL(blob))
            : reject(new Error("toBlob failed")),
        "image/png"
      )
    }
    img.onerror = reject
    img.src = src
  })
}

async function generateAll(
  master: string
): Promise<Partial<Record<BrandKey, string>>> {
  const entries = await Promise.all(
    ASSETS.map(async (a) => [a.key, await resizeTo(master, a.size)] as const)
  )
  return Object.fromEntries(entries)
}

interface Props {
  branding: Branding
  onChange: (next: Branding) => void
  canEdit: boolean
}

export function CompanyBranding({ branding, onChange, canEdit }: Props) {
  // One crop pipeline; `target` is "master" or a specific asset being overridden.
  const [cropSrc, setCropSrc] = useState<string | null>(null)
  const [target, setTarget] = useState<"master" | BrandKey | null>(null)
  const [busy, setBusy] = useState(false)

  const masterInputRef = useRef<HTMLInputElement>(null)

  const read = (file: File, t: "master" | BrandKey) => {
    const reader = new FileReader()
    reader.onload = () => {
      setCropSrc(reader.result as string)
      setTarget(t)
    }
    reader.readAsDataURL(file)
  }

  const reset = () => {
    setCropSrc(null)
    setTarget(null)
  }

  const onCropDone = async (url: string) => {
    if (target === "master") {
      setBusy(true)
      const generated = await generateAll(url)
      onChange({ master: url, generated, overrides: branding.overrides })
      setBusy(false)
    } else if (target) {
      onChange({
        ...branding,
        overrides: { ...branding.overrides, [target]: url },
      })
    }
    reset()
  }

  const regenerate = async () => {
    if (!branding.master) return
    setBusy(true)
    const generated = await generateAll(branding.master)
    onChange({ ...branding, generated })
    setBusy(false)
  }

  const clearOverride = (key: BrandKey) => {
    const overrides = { ...branding.overrides }
    delete overrides[key]
    onChange({ ...branding, overrides })
  }

  const removeMaster = () => onChange(EMPTY_BRANDING)

  return (
    <>
      <PhotoCropModal imageSrc={cropSrc} onDone={onCropDone} onCancel={reset} />

      {/* ── Master image ───────────────────────────────────────────── */}
      <div className="flex items-center gap-4 rounded-xl border border-border bg-muted/30 p-4">
        <div className="flex size-16 shrink-0 items-center justify-center overflow-hidden rounded-xl bg-muted ring-1 ring-border">
          {branding.master ? (
            // eslint-disable-next-line @next/next/no-img-element
            <img
              src={branding.master}
              alt="Brand image"
              className="size-full object-cover"
            />
          ) : (
            <HugeiconsIcon
              icon={Image01Icon}
              size={20}
              strokeWidth={1.8}
              className="text-muted-foreground/50"
            />
          )}
        </div>

        <div className="min-w-0 flex-1">
          <div className="flex items-center gap-1.5">
            <HugeiconsIcon
              icon={MagicWand01Icon}
              size={13}
              strokeWidth={2}
              className="text-primary"
            />
            <p className="text-[13px] font-semibold text-foreground">
              Brand image
            </p>
          </div>
          <p className="text-[11.5px] text-muted-foreground">
            Upload once — your favicon, sidebar mark and app icon are generated
            automatically.
          </p>

          {canEdit && (
            <div className="mt-2 flex flex-wrap items-center gap-1.5">
              <input
                ref={masterInputRef}
                type="file"
                accept="image/png, image/jpeg, image/svg+xml"
                className="hidden"
                onChange={(e) => {
                  const file = e.target.files?.[0]
                  if (file) read(file, "master")
                  e.target.value = ""
                }}
              />
              <Button
                size="sm"
                className="h-7 text-[12px]"
                onClick={() => masterInputRef.current?.click()}
              >
                <HugeiconsIcon
                  icon={Upload03Icon}
                  size={13}
                  strokeWidth={2}
                  className="mr-1"
                />
                {branding.master ? "Replace image" : "Upload image"}
              </Button>
              {branding.master && (
                <>
                  <Button
                    size="sm"
                    variant="outline"
                    className="h-7 text-[12px]"
                    onClick={regenerate}
                    disabled={busy}
                  >
                    <HugeiconsIcon
                      icon={ReloadIcon}
                      size={13}
                      strokeWidth={2}
                      className="mr-1"
                    />
                    {busy ? "Generating…" : "Regenerate"}
                  </Button>
                  <Button
                    size="sm"
                    variant="ghost"
                    className="h-7 text-[12px] text-muted-foreground hover:text-destructive"
                    onClick={removeMaster}
                  >
                    <HugeiconsIcon
                      icon={Delete02Icon}
                      size={13}
                      strokeWidth={2}
                      className="mr-1"
                    />
                    Clear all
                  </Button>
                </>
              )}
            </div>
          )}
        </div>
      </div>

      {/* ── Generated assets ───────────────────────────────────────── */}
      <div className="mt-3 grid gap-3 sm:grid-cols-2">
        {ASSETS.map((a) => (
          <AssetSlot
            key={a.key}
            label={a.label}
            hint={a.hint}
            value={resolveAsset(branding, a.key)}
            overridden={a.key in branding.overrides}
            canEdit={canEdit}
            onPick={(file) => read(file, a.key)}
            onReset={() => clearOverride(a.key)}
          />
        ))}
      </div>
    </>
  )
}

function AssetSlot({
  label,
  hint,
  value,
  overridden,
  canEdit,
  onPick,
  onReset,
}: {
  label: string
  hint: string
  value: string | null
  overridden: boolean
  canEdit: boolean
  onPick: (file: File) => void
  onReset: () => void
}) {
  const inputRef = useRef<HTMLInputElement>(null)

  return (
    <div className="flex items-center gap-4 rounded-xl border border-border bg-card p-4">
      <div className="flex size-12 shrink-0 items-center justify-center overflow-hidden rounded-lg bg-muted ring-1 ring-border">
        {value ? (
          // eslint-disable-next-line @next/next/no-img-element
          <img src={value} alt={label} className="size-full object-cover" />
        ) : (
          <HugeiconsIcon
            icon={Image01Icon}
            size={16}
            strokeWidth={1.8}
            className="text-muted-foreground/50"
          />
        )}
      </div>

      <div className="min-w-0 flex-1">
        <div className="flex items-center gap-2">
          <p className="truncate text-[13px] font-medium text-foreground">
            {label}
          </p>
          {value && (
            <span
              className={
                overridden
                  ? "rounded bg-amber-500/15 px-1.5 py-0.5 text-[10px] font-medium text-amber-600 dark:text-amber-400"
                  : "rounded bg-primary/10 px-1.5 py-0.5 text-[10px] font-medium text-primary"
              }
            >
              {overridden ? "Custom" : "Auto"}
            </span>
          )}
        </div>
        <p className="text-[11px] text-muted-foreground">{hint}</p>

        {canEdit && (
          <div className="mt-1.5 flex items-center gap-1.5">
            <input
              ref={inputRef}
              type="file"
              accept="image/png, image/jpeg, image/svg+xml"
              className="hidden"
              onChange={(e) => {
                const file = e.target.files?.[0]
                if (file) onPick(file)
                e.target.value = ""
              }}
            />
            <Button
              size="sm"
              variant="ghost"
              className="h-6 px-2 text-[11.5px]"
              onClick={() => inputRef.current?.click()}
            >
              {value ? "Replace" : "Upload"}
            </Button>
            {overridden && (
              <Button
                size="sm"
                variant="ghost"
                className="h-6 px-2 text-[11.5px] text-muted-foreground"
                onClick={onReset}
              >
                Reset to auto
              </Button>
            )}
          </div>
        )}
      </div>
    </div>
  )
}
